INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('신라호텔', '서울의 5성급 호텔', '예약 후 문자 드림', true, 'MACHINE', 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('롯데호텔', '도심 속 럭셔리 호텔', '정문에서 우회전', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('경주한옥스테이', '경주의 전통 한옥 체험', '역에서 도보 10분', true, 'ETC', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('제주 라마다 호텔', '제주의 멋진 해변 전망 호텔', '공항 셔틀 제공', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('부산 파라다이스 호텔', '해운대 해변에 위치한 최고급 호텔', '지하철 1번 출구 도보 5분', true, 'FIELD', 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('강릉 펜션', '강릉 바다와 가까운 펜션', '해변에서 도보 10분', true, 'FIELD', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('인천 공항 호텔', '인천 국제공항과 가까운 호텔', '공항 셔틀 서비스 제공', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('속초 해변 리조트', '속초의 해변 바로 앞 리조트', '속초역에서 버스 10분', true, 'FIELD', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('전주 한옥마을 숙박', '전주 한옥마을 내 위치한 전통 숙소', '한옥마을 내 도보 이동 가능', true, 'ETC', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('대구 프리미어 호텔', '대구 중심부에 위치한 비즈니스 호텔', '지하철 2호선 도보 3분', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('서울 명동 게스트하우스', '명동 중심부에 위치한 게스트하우스', '명동역 5번 출구 도보 2분', true, 'ETC', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('여수 오션뷰 호텔', '여수의 아름다운 바다 전망 호텔', '여수역에서 택시 10분', true, 'FIELD', 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('포항 비즈니스 호텔', '포항 시내에 위치한 비즈니스 호텔', '포항역에서 도보 15분', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('강릉 오션 리조트', '강릉 바닷가에 위치한 리조트', '버스터미널에서 택시 10분', true, 'FIELD', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('대전 게스트하우스', '대전 중심부에 위치한 게스트하우스', '대전역 도보 5분 거리', true, 'ETC', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('서울 남산 호텔', '남산 전망의 고급 호텔', '남산 케이블카 도보 5분', false, 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('광주 컨벤션 호텔', '광주 컨벤션 센터 근처 비즈니스 호텔', '광주역 도보 10분', true, 'FIELD', 'HOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('경주 리조트', '경주의 역사를 느낄 수 있는 리조트', '경주역에서 버스 20분', true, 'FIELD', 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, accommodation_Type) VALUES ('전주 펜션', '전주의 조용한 교외에 위치한 펜션', '전주역에서 택시 15분', false, 'MOTEL');
INSERT INTO accommodation (name, description, location_Guide_Text, is_Free_Parking, parking_Type, accommodation_Type) VALUES ('부산 오션 리조트', '부산 해운대 해변 앞 리조트', '해운대역 도보 10분', true, 'MACHINE', 'MOTEL');
